#!/usr/bin/env python3
"""Generate checked-in SDK operation stubs from a minimal OpenAPI YAML/JSON stub.

Role: deterministic codegen for paths/methods/operationIds into sdk/generated/.
SoT: openapi-stub.yaml (or --input). Never invents endpoints beyond the stub.
Allowed failure: exit non-zero on missing/invalid stub. Forbidden: network fetch.
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parents[3]
DEFAULT_INPUT = Path(__file__).resolve().parent / "openapi-stub.yaml"
DEFAULT_OUT = ROOT / "backend" / "packages" / "sdk" / "generated"


def _load_stub(path: Path) -> dict[str, Any]:
    text = path.read_text(encoding="utf-8")
    if path.suffix.lower() in {".yaml", ".yml"}:
        try:
            import yaml  # type: ignore
        except ImportError:
            return _parse_minimal_yaml(text)
        data = yaml.safe_load(text)
    else:
        data = json.loads(text)
    if not isinstance(data, dict):
        raise ValueError("OpenAPI stub must be a mapping")
    return data


def _parse_minimal_yaml(text: str) -> dict[str, Any]:
    """Tiny subset parser when PyYAML is unavailable: openapi info + paths only."""
    paths: dict[str, dict[str, Any]] = {}
    current_path: str | None = None
    current_method: str | None = None
    in_paths = False
    for raw in text.splitlines():
        line = raw.rstrip()
        if not line.strip() or line.strip().startswith("#"):
            continue
        if line.startswith("paths:"):
            in_paths = True
            continue
        if not in_paths:
            continue
        path_match = re.match(r"^  (/[^:]+):\s*$", line)
        if path_match:
            current_path = path_match.group(1)
            paths[current_path] = {}
            current_method = None
            continue
        method_match = re.match(r"^    (get|post|put|patch|delete):\s*$", line, re.I)
        if method_match and current_path:
            current_method = method_match.group(1).lower()
            paths[current_path][current_method] = {}
            continue
        op_match = re.match(r'^      operationId:\s*["\']?([\w.]+)["\']?\s*$', line)
        if op_match and current_path and current_method:
            paths[current_path][current_method]["operationId"] = op_match.group(1)
            continue
        sum_match = re.match(r'^      summary:\s*["\']?(.+?)["\']?\s*$', line)
        if sum_match and current_path and current_method:
            paths[current_path][current_method]["summary"] = sum_match.group(1)
    return {"openapi": "3.0.3", "paths": paths}


def extract_operations(spec: dict[str, Any]) -> list[dict[str, str]]:
    paths = spec.get("paths") or {}
    if not isinstance(paths, dict) or not paths:
        raise ValueError("OpenAPI stub has no paths")
    ops: list[dict[str, str]] = []
    http_methods = {"get", "post", "put", "patch", "delete", "head", "options"}
    for path, item in sorted(paths.items()):
        if not isinstance(item, dict):
            continue
        for method, op in sorted(item.items()):
            if method.lower() not in http_methods or not isinstance(op, dict):
                continue
            op_id = str(op.get("operationId") or f"{method}_{path}").replace("/", "_")
            ops.append(
                {
                    "operation_id": op_id,
                    "method": method.upper(),
                    "path": str(path),
                    "summary": str(op.get("summary") or ""),
                }
            )
    if not ops:
        raise ValueError("OpenAPI stub yielded zero operations")
    return ops


def render_python(ops: list[dict[str, str]]) -> str:
    lines = [
        '"""AUTO-GENERATED by backend/tools/sdk-generation/generate.py — do not edit."""',
        "",
        "from __future__ import annotations",
        "",
        "OPERATIONS: list[dict[str, str]] = [",
    ]
    for op in ops:
        lines.append(
            "    {"
            f'"operation_id": {op["operation_id"]!r}, '
            f'"method": {op["method"]!r}, '
            f'"path": {op["path"]!r}, '
            f'"summary": {op["summary"]!r}'
            "},"
        )
    lines.append("]")
    lines.append("")
    lines.append("__all__ = [\"OPERATIONS\"]")
    lines.append("")
    return "\n".join(lines)


def render_typescript(ops: list[dict[str, str]]) -> str:
    lines = [
        "/* AUTO-GENERATED by backend/tools/sdk-generation/generate.py — do not edit. */",
        "",
        "export type GeneratedOperation = {",
        "  operationId: string;",
        "  method: string;",
        "  path: string;",
        "  summary: string;",
        "};",
        "",
        "export const OPERATIONS: GeneratedOperation[] = [",
    ]
    for op in ops:
        lines.append(
            "  {"
            f' operationId: {json.dumps(op["operation_id"])},'
            f' method: {json.dumps(op["method"])},'
            f' path: {json.dumps(op["path"])},'
            f' summary: {json.dumps(op["summary"])} '
            "},"
        )
    lines.append("];")
    lines.append("")
    return "\n".join(lines)


def render_manifest(ops: list[dict[str, str]], source: str) -> str:
    payload = {
        "generator": "backend/tools/sdk-generation/generate.py",
        "source": source,
        "operation_count": len(ops),
        "operations": ops,
    }
    return json.dumps(payload, indent=2, sort_keys=True) + "\n"


def write_outputs(out_dir: Path, ops: list[dict[str, str]], source: str) -> None:
    out_dir.mkdir(parents=True, exist_ok=True)
    (out_dir / "operations.py").write_text(render_python(ops), encoding="utf-8")
    (out_dir / "operations.ts").write_text(render_typescript(ops), encoding="utf-8")
    (out_dir / "manifest.json").write_text(
        render_manifest(ops, source), encoding="utf-8"
    )
    init = out_dir / "__init__.py"
    if not init.exists():
        init.write_text(
            '"""Generated SDK stubs. Regenerate via sdk-generation/generate.py."""\n'
            "from .operations import OPERATIONS\n\n"
            '__all__ = ["OPERATIONS"]\n',
            encoding="utf-8",
        )


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--input", type=Path, default=DEFAULT_INPUT)
    parser.add_argument("--out", type=Path, default=DEFAULT_OUT)
    parser.add_argument(
        "--check",
        action="store_true",
        help="Validate on-disk stubs match regeneration without writing",
    )
    args = parser.parse_args(argv)
    spec = _load_stub(args.input)
    ops = extract_operations(spec)
    source = str(args.input.relative_to(ROOT) if args.input.is_relative_to(ROOT) else args.input)
    if args.check:
        expected_py = render_python(ops)
        expected_ts = render_typescript(ops)
        expected_manifest = render_manifest(ops, source)
        actual_py = (args.out / "operations.py").read_text(encoding="utf-8")
        actual_ts = (args.out / "operations.ts").read_text(encoding="utf-8")
        actual_manifest = (args.out / "manifest.json").read_text(encoding="utf-8")
        if (
            actual_py != expected_py
            or actual_ts != expected_ts
            or actual_manifest != expected_manifest
        ):
            print("generated SDK stubs are out of date; re-run generate.py", file=sys.stderr)
            return 1
        print(f"ok: {len(ops)} operations match")
        return 0
    write_outputs(args.out, ops, source)
    print(f"wrote {len(ops)} operations to {args.out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
