"""Local-dev process control: Compose core infra + MCP HTTP daemon + systemd boot.

Public API is re-exported here so callers keep using ``astloom_cli.service_runtime``.
"""

from __future__ import annotations

from astloom_cli.service_runtime.boot import (
    astloom_bin,
    boot_disable,
    boot_enable,
    boot_status,
    systemctl as _systemctl,
    unit_body,
    unit_path,
)
from astloom_cli.service_runtime.compose import (
    compose_base_cmd,
    compose_logs_tail,
    compose_status,
    container_started_at,
    run_cmd as _run,
    start_compose,
    stop_compose,
    stop_mcp_gateway,
)
from astloom_cli.service_runtime.https_apis import (
    https_apis_status,
    read_code_graph_pid,
    read_https_api_pids,
    start_https_apis,
    stop_https_apis,
)
from astloom_cli.service_runtime.lifecycle import (
    ensure_running_or_offer_start,
    restart_all,
    service_state,
    start_all,
    status_all,
    stop_all,
)
from astloom_cli.service_runtime.logs import collect_detail, dump_json, read_log_tail
from astloom_cli.service_runtime.mcp import (
    mcp_status,
    pid_alive as _pid_alive,
    prepare_mcp_env,
    read_mcp_pid,
    start_mcp_http,
    stop_mcp_http,
    tcp_ok as _tcp_ok,
)
from astloom_cli.service_runtime.paths import (
    CODE_GRAPH_READY_TIMEOUT_SEC,
    COMPOSE_SERVICES,
    DEFAULT_CODE_GRAPH_HOST,
    DEFAULT_CODE_GRAPH_PORT,
    DEFAULT_MCP_HOST,
    DEFAULT_MCP_PORT,
    DEFAULT_PROJECT_PROFILE_PORT,
    UNIT_NAME,
    code_graph_log_path,
    code_graph_pid_path,
    compose_dir,
    compose_env_file,
    compose_file,
    install_role,
    local_compose_stack_present,
    mcp_log_path,
    mcp_pid_path,
    mcp_secret_path,
    missing_local_stack_message,
    project_profile_log_path,
    project_profile_pid_path,
    run_dir,
)
from astloom_cli.service_runtime.progress import (
    format_docker_started_at as _format_docker_started_at,
    format_process_started_at,
    progress as _progress,
    stack_restarted_at,
    uptime_seconds_since,
    wall_clock_now,
)

__all__ = [
    "CODE_GRAPH_READY_TIMEOUT_SEC",
    "COMPOSE_SERVICES",
    "DEFAULT_CODE_GRAPH_HOST",
    "DEFAULT_CODE_GRAPH_PORT",
    "DEFAULT_MCP_HOST",
    "DEFAULT_MCP_PORT",
    "DEFAULT_PROJECT_PROFILE_PORT",
    "UNIT_NAME",
    "_format_docker_started_at",
    "_pid_alive",
    "_progress",
    "_run",
    "_systemctl",
    "_tcp_ok",
    "astloom_bin",
    "boot_disable",
    "boot_enable",
    "boot_status",
    "code_graph_log_path",
    "code_graph_pid_path",
    "collect_detail",
    "compose_base_cmd",
    "compose_dir",
    "compose_env_file",
    "compose_file",
    "compose_logs_tail",
    "compose_status",
    "container_started_at",
    "dump_json",
    "ensure_running_or_offer_start",
    "format_process_started_at",
    "https_apis_status",
    "install_role",
    "local_compose_stack_present",
    "mcp_log_path",
    "mcp_pid_path",
    "mcp_secret_path",
    "mcp_status",
    "missing_local_stack_message",
    "prepare_mcp_env",
    "project_profile_log_path",
    "project_profile_pid_path",
    "read_code_graph_pid",
    "read_https_api_pids",
    "read_log_tail",
    "read_mcp_pid",
    "restart_all",
    "run_dir",
    "service_state",
    "stack_restarted_at",
    "start_all",
    "start_compose",
    "start_https_apis",
    "start_mcp_http",
    "status_all",
    "stop_all",
    "stop_compose",
    "stop_https_apis",
    "stop_mcp_gateway",
    "stop_mcp_http",
    "unit_body",
    "unit_path",
    "uptime_seconds_since",
    "wall_clock_now",
]
