from __future__ import annotations

from typing import Any, Protocol

from .enums import TicketState
from .models import (
    AdapterMapping,
    BrokerEvent,
    Connector,
    DeadLetterRecord,
    Delivery,
    DepartmentTask,
    DispatchAck,
    ExternalTicket,
    Scope,
    Subscription,
)


class Store(Protocol):
    def get_connector(self, connector_id: str, scope: Scope) -> Connector: ...
    def put_connector(self, connector: Connector) -> None: ...
    def list_connectors(self, scope: Scope) -> list[Connector]: ...
    def put_mapping(self, mapping: AdapterMapping) -> None: ...
    def list_mappings(self, scope: Scope, connector_id: str | None = None) -> list[AdapterMapping]: ...
    def get_subscription(self, subscription_id: str, scope: Scope) -> Subscription: ...
    def put_subscription(self, subscription: Subscription) -> None: ...
    def list_subscriptions(self, scope: Scope) -> list[Subscription]: ...
    def put_event(self, event: BrokerEvent) -> None: ...
    def list_events(self, scope: Scope, channel: str | None = None) -> list[BrokerEvent]: ...
    def get_event(self, event_id: str, scope: Scope) -> BrokerEvent: ...
    def put_delivery(self, delivery: Delivery) -> None: ...
    def list_deliveries(self, scope: Scope) -> list[Delivery]: ...
    def put_dead_letter(self, record: DeadLetterRecord) -> None: ...
    def list_dead_letters(self, scope: Scope) -> list[DeadLetterRecord]: ...
    def get_ticket(self, ticket_id: str, scope: Scope) -> ExternalTicket: ...
    def put_ticket(self, ticket: ExternalTicket, expected_version: int | None = None) -> None: ...
    def list_tickets(
        self,
        scope: Scope,
        *,
        connector_id: str | None = None,
        status: str | None = None,
        external_ref: str | None = None,
        department: str | None = None,
        updated_after: str | None = None,
        page_size: int = 50,
        page_token: str | None = None,
    ) -> tuple[list[ExternalTicket], str | None]: ...
    def put_department_task(self, task: DepartmentTask) -> None: ...
    def list_department_tasks(self, scope: Scope) -> list[DepartmentTask]: ...
    def idempotent(self, scope: Scope, command: str, key: str, payload: dict[str, Any]) -> str | None: ...
    def remember(self, scope: Scope, command: str, key: str, payload: dict[str, Any], record_id: str) -> None: ...
    def event(self, payload: dict[str, Any]) -> None: ...
    def outbox(self) -> list[dict[str, Any]]: ...


class TrackerAdapter(Protocol):
    vendor: str

    def create_remote(
        self,
        ticket: ExternalTicket,
        connector: Connector,
        mapping: AdapterMapping,
    ) -> DispatchAck: ...

    def update_remote_status(
        self,
        ticket: ExternalTicket,
        connector: Connector,
        mapping: AdapterMapping,
        status: TicketState,
    ) -> DispatchAck: ...
