"""Persistence port for docs-sync (Phase C DI hygiene).

Role: define the ``Store`` protocol used by ``DocsSyncService``.
Source of truth: this module; concrete adapters live in ``postgres_store`` /
``testing`` and must be constructed only from ``bootstrap`` (or tests).
Allowed: protocol-only surface for application code. Forbidden: importing
Postgres/HTTP adapters from API handlers or domain helpers.
"""

from __future__ import annotations

from typing import Any, Protocol

from .models import (
    CodeSymbol,
    DocAnchor,
    Document,
    DocumentationDraft,
    DriftFinding,
    Scope,
)


class Store(Protocol):
    def get_symbol(self, symbol_id: str, scope: Scope) -> CodeSymbol: ...
    def find_symbol(self, scope: Scope, repo: str, file_path: str, symbol_path: str) -> CodeSymbol | None: ...
    def put_symbol(self, symbol: CodeSymbol) -> None: ...
    def delete_symbol(self, symbol_id: str, scope: Scope) -> None: ...
    def list_symbols(self, scope: Scope) -> list[CodeSymbol]: ...
    def get_document(self, document_id: str, scope: Scope) -> Document: ...
    def put_document(self, document: Document) -> None: ...
    def list_documents(self, scope: Scope) -> list[Document]: ...
    def get_anchor(self, anchor_id: str, scope: Scope) -> DocAnchor: ...
    def put_anchor(self, anchor: DocAnchor) -> None: ...
    def delete_anchor(self, anchor_id: str, scope: Scope) -> None: ...
    def list_anchors(self, scope: Scope, symbol_id: str | None = None) -> list[DocAnchor]: ...
    def get_finding(self, finding_id: str, scope: Scope) -> DriftFinding: ...
    def put_finding(self, finding: DriftFinding) -> None: ...
    def list_findings(self, scope: Scope) -> list[DriftFinding]: ...
    def get_draft(self, draft_id: str, scope: Scope) -> DocumentationDraft: ...
    def put_draft(self, draft: DocumentationDraft) -> None: ...
    def list_drafts(self, scope: Scope) -> list[DocumentationDraft]: ...
    def idempotent(self, scope: Scope, command: str, key: str, payload: dict[str, Any]) -> str | None: ...
    def remember(self, scope: Scope, command: str, key: str, payload: dict[str, Any], record_id: str) -> None: ...
    def event(self, payload: dict[str, Any]) -> None: ...
    def outbox(self) -> list[dict[str, Any]]: ...


__all__ = ["Store"]
