"""Store port for memory persistence and outbox."""

from __future__ import annotations

from typing import Any, Protocol

from .models import MemoryItem, QuestionMemory, Scope, WorkBatch


class Store(Protocol):
    def get_memory(self, memory_id: str, scope: Scope) -> MemoryItem: ...
    def put_memory(self, item: MemoryItem) -> None: ...
    def list_memory(self, scope: Scope) -> list[MemoryItem]: ...
    def get_question(self, question_id: str, scope: Scope) -> QuestionMemory: ...
    def find_question(self, normalized: str, scope: Scope) -> QuestionMemory | None: ...
    def put_question(self, question: QuestionMemory) -> None: ...
    def list_questions(self, scope: Scope) -> list[QuestionMemory]: ...
    def get_batch(self, batch_id: str, scope: Scope) -> WorkBatch: ...
    def put_batch(self, batch: WorkBatch) -> None: ...
    def list_batches(self, scope: Scope) -> list[WorkBatch]: ...
    def idempotent(self, scope: Scope, command: str, key: str, payload: dict[str, Any]) -> str | None: ...
    def remember(self, scope: Scope, command: str, key: str, payload: dict[str, Any], record_id: str) -> None: ...
    def event(self, payload: dict[str, Any]) -> None: ...
    def outbox(self) -> list[dict[str, Any]]: ...
