"""Persistence port for rule-engine."""

from __future__ import annotations

from typing import Any, Protocol

from .models import (
    AnomalySignal,
    ApprovalRequest,
    ImpactMap,
    RoutedTask,
    Rule,
    RuleEvaluation,
    RuleFeedback,
    Scope,
)


class Store(Protocol):
    def get_rule(self, rule_id: str, scope: Scope) -> Rule: ...
    def put_rule(self, rule: Rule) -> None: ...
    def list_rules(self, scope: Scope) -> list[Rule]: ...
    def get_evaluation(self, evaluation_id: str, scope: Scope) -> RuleEvaluation: ...
    def put_evaluation(self, evaluation: RuleEvaluation) -> None: ...
    def list_evaluations(self, scope: Scope) -> list[RuleEvaluation]: ...
    def get_approval(self, approval_id: str, scope: Scope) -> ApprovalRequest: ...
    def put_approval(self, approval: ApprovalRequest) -> None: ...
    def list_approvals(self, scope: Scope) -> list[ApprovalRequest]: ...
    def put_task(self, task: RoutedTask) -> None: ...
    def list_tasks(self, scope: Scope) -> list[RoutedTask]: ...
    def put_anomaly(self, anomaly: AnomalySignal) -> None: ...
    def list_anomalies(self, scope: Scope) -> list[AnomalySignal]: ...
    def put_feedback(self, feedback: RuleFeedback) -> None: ...
    def list_feedback(self, scope: Scope) -> list[RuleFeedback]: ...
    def put_impact(self, impact: ImpactMap) -> None: ...
    def list_impacts(self, scope: Scope) -> list[ImpactMap]: ...
    def idempotent(self, scope: Scope, command: str, key: str, payload: dict[str, Any]) -> str | None: ...
    def remember(self, scope: Scope, command: str, key: str, payload: dict[str, Any], record_id: str) -> None: ...
    def event(self, payload: dict[str, Any]) -> None: ...
    def outbox(self) -> list[dict[str, Any]]: ...
